'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace NRCS_Service
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://SDMDataAccess.nrcs.usda.gov/Tabular/SDMTabularService.asmx", ConfigurationName:="NRCS_Service.SDMTabularServiceSoap")>  _
    Public Interface SDMTabularServiceSoap
        
        'CODEGEN: Generating message contract since element name Query from namespace http://SDMDataAccess.nrcs.usda.gov/Tabular/SDMTabularService.asmx is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://SDMDataAccess.nrcs.usda.gov/Tabular/SDMTabularService.asmx/RunQuery", ReplyAction:="*")>  _
        Function RunQuery(ByVal request As NRCS_Service.RunQueryRequest) As NRCS_Service.RunQueryResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class RunQueryRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="RunQuery", [Namespace]:="http://SDMDataAccess.nrcs.usda.gov/Tabular/SDMTabularService.asmx", Order:=0)>  _
        Public Body As NRCS_Service.RunQueryRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As NRCS_Service.RunQueryRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://SDMDataAccess.nrcs.usda.gov/Tabular/SDMTabularService.asmx")>  _
    Partial Public Class RunQueryRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Query As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Query As String)
            MyBase.New
            Me.Query = Query
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class RunQueryResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="RunQueryResponse", [Namespace]:="http://SDMDataAccess.nrcs.usda.gov/Tabular/SDMTabularService.asmx", Order:=0)>  _
        Public Body As NRCS_Service.RunQueryResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As NRCS_Service.RunQueryResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://SDMDataAccess.nrcs.usda.gov/Tabular/SDMTabularService.asmx")>  _
    Partial Public Class RunQueryResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public RunQueryResult As System.Data.DataSet
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal RunQueryResult As System.Data.DataSet)
            MyBase.New
            Me.RunQueryResult = RunQueryResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface SDMTabularServiceSoapChannel
        Inherits NRCS_Service.SDMTabularServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class SDMTabularServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of NRCS_Service.SDMTabularServiceSoap)
        Implements NRCS_Service.SDMTabularServiceSoap
        
        Public Sub New()
            MyBase.New
        End Sub

        'Public Sub New(ByVal endpointConfigurationName As String)
        '    MyBase.New(endpointConfigurationName)
        'End Sub

        'Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
        '    MyBase.New(endpointConfigurationName, remoteAddress)
        'End Sub

        'Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
        '    MyBase.New(endpointConfigurationName, remoteAddress)
        'End Sub

        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NRCS_Service_SDMTabularServiceSoap_RunQuery(ByVal request As NRCS_Service.RunQueryRequest) As NRCS_Service.RunQueryResponse Implements NRCS_Service.SDMTabularServiceSoap.RunQuery
            Return MyBase.Channel.RunQuery(request)
        End Function
        
        Public Function RunQuery(ByVal Query As String) As System.Data.DataSet
            Dim inValue As NRCS_Service.RunQueryRequest = New NRCS_Service.RunQueryRequest()
            inValue.Body = New NRCS_Service.RunQueryRequestBody()
            inValue.Body.Query = Query
            Dim retVal As NRCS_Service.RunQueryResponse = CType(Me,NRCS_Service.SDMTabularServiceSoap).RunQuery(inValue)
            Return retVal.Body.RunQueryResult
        End Function
    End Class
End Namespace
