'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.296
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace NRCS_Service
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://SDMDataAccess.nrcs.usda.gov/Tabular/SDMTabularService.asmx", ConfigurationName:="NRCS_Service.SDMTabularServiceSoap")>  _
    Public Interface SDMTabularServiceSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://SDMDataAccess.nrcs.usda.gov/Tabular/SDMTabularService.asmx/RunQuery", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function RunQuery(ByVal Query As String) As System.Data.DataSet
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface SDMTabularServiceSoapChannel
        Inherits NRCS_Service.SDMTabularServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class SDMTabularServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of NRCS_Service.SDMTabularServiceSoap)
        Implements NRCS_Service.SDMTabularServiceSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function RunQuery(ByVal Query As String) As System.Data.DataSet Implements NRCS_Service.SDMTabularServiceSoap.RunQuery
            Return MyBase.Channel.RunQuery(Query)
        End Function
    End Class
End Namespace
