'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.296
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace StationService
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://stationservice.storet.epa.gov/", ConfigurationName:="StationService.StationService")>  _
    Public Interface StationService
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.DataContractFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc)>  _
        Function getStationCount(ByVal MinimumLatitude As Double, ByVal MaximumLatitude As Double, ByVal MinimumLongitude As Double, ByVal MaximumLongitude As Double) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Long
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.DataContractFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc)>  _
        Function getStationsForMap(ByVal MinimumLatitude As Double, ByVal MaximumLatitude As Double, ByVal MinimumLongitude As Double, ByVal MaximumLongitude As Double) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> String
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.DataContractFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc)>  _
        Function getStationCharacteristicsForMap(ByVal MinimumLatitude As Double, ByVal MaximumLatitude As Double, ByVal MinimumLongitude As Double, ByVal MaximumLongitude As Double) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> String
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.DataContractFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc)>  _
        Function getStationInfo(ByVal StationIdentifiersInputString As String) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> String
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface StationServiceChannel
        Inherits StationService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class StationServiceClient
        Inherits System.ServiceModel.ClientBase(Of StationService)
        Implements StationService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function getStationCount(ByVal MinimumLatitude As Double, ByVal MaximumLatitude As Double, ByVal MinimumLongitude As Double, ByVal MaximumLongitude As Double) As Long Implements StationService.getStationCount
            Return MyBase.Channel.getStationCount(MinimumLatitude, MaximumLatitude, MinimumLongitude, MaximumLongitude)
        End Function
        
        Public Function getStationsForMap(ByVal MinimumLatitude As Double, ByVal MaximumLatitude As Double, ByVal MinimumLongitude As Double, ByVal MaximumLongitude As Double) As String Implements StationService.getStationsForMap
            Return MyBase.Channel.getStationsForMap(MinimumLatitude, MaximumLatitude, MinimumLongitude, MaximumLongitude)
        End Function
        
        Public Function getStationCharacteristicsForMap(ByVal MinimumLatitude As Double, ByVal MaximumLatitude As Double, ByVal MinimumLongitude As Double, ByVal MaximumLongitude As Double) As String Implements StationService.getStationCharacteristicsForMap
            Return MyBase.Channel.getStationCharacteristicsForMap(MinimumLatitude, MaximumLatitude, MinimumLongitude, MaximumLongitude)
        End Function
        
        Public Function getStationInfo(ByVal StationIdentifiersInputString As String) As String Implements StationService.getStationInfo
            Return MyBase.Channel.getStationInfo(StationIdentifiersInputString)
        End Function
    End Class
End Namespace
