//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D4EM_NRCS_Soil.NRCS.SDMTabularServiceSoap {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://SDMDataAccess.nrcs.usda.gov/Tabular/SDMTabularService.asmx", ConfigurationName="NRCS.SDMTabularServiceSoap.SDMTabularServiceSoap")]
    public interface SDMTabularServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SDMDataAccess.nrcs.usda.gov/Tabular/SDMTabularService.asmx/RunQuery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet RunQuery(string Query);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SDMTabularServiceSoapChannel : D4EM_NRCS_Soil.NRCS.SDMTabularServiceSoap.SDMTabularServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SDMTabularServiceSoapClient : System.ServiceModel.ClientBase<D4EM_NRCS_Soil.NRCS.SDMTabularServiceSoap.SDMTabularServiceSoap>, D4EM_NRCS_Soil.NRCS.SDMTabularServiceSoap.SDMTabularServiceSoap {
        
        public SDMTabularServiceSoapClient() {
        }
        
        public SDMTabularServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SDMTabularServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SDMTabularServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SDMTabularServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet RunQuery(string Query) {
            return base.Channel.RunQuery(Query);
        }
    }
}
