'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ResultServiceReference
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://storetresultservice.storet.epa.gov/", ConfigurationName:="ResultServiceReference.StoretResultService")>  _
    Public Interface StoretResultService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://storetresultservice.storet.epa.gov/StoretResultService/getResultsRequest", ReplyAction:="http://storetresultservice.storet.epa.gov/StoretResultService/getResultsResponse"),  _
         System.ServiceModel.DataContractFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc)>  _
        Function getResults(ByVal OrganizationId As String, ByVal MonitoringLocationId As String, ByVal MonitoringLocationType As String, ByVal MinimumActivityStartDate As String, ByVal MaximumActivityStartDate As String, ByVal MinimumLatitude As String, ByVal MaximumLatitude As String, ByVal MinimumLongitude As String, ByVal MaximumLongitude As String, ByVal CharacteristicType As String, ByVal CharacteristicName As String, ByVal ResultType As String) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://storetresultservice.storet.epa.gov/StoretResultService/getResultCountReque"& _ 
            "st", ReplyAction:="http://storetresultservice.storet.epa.gov/StoretResultService/getResultCountRespo"& _ 
            "nse"),  _
         System.ServiceModel.DataContractFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc)>  _
        Function getResultCount(ByVal OrganizationId As String, ByVal MonitoringLocationId As String, ByVal MonitoringLocationType As String, ByVal MinimumActivityStartDate As String, ByVal MaximumActivityStartDate As String, ByVal MinimumLatitude As String, ByVal MaximumLatitude As String, ByVal MinimumLongitude As String, ByVal MaximumLongitude As String, ByVal CharacteristicType As String, ByVal CharacteristicName As String, ByVal ResultType As String) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://storetresultservice.storet.epa.gov/StoretResultService/getActivityCountReq"& _ 
            "uest", ReplyAction:="http://storetresultservice.storet.epa.gov/StoretResultService/getActivityCountRes"& _ 
            "ponse"),  _
         System.ServiceModel.DataContractFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc)>  _
        Function getActivityCount(ByVal OrganizationId As String, ByVal ActivityId As String, ByVal ActivityType As String, ByVal MonitoringLocationId As String, ByVal MonitoringLocationType As String, ByVal ProjectId As String, ByVal MinimumActivityStartDate As String, ByVal MaximumActivityStartDate As String, ByVal CharacteristicType As String, ByVal CharacteristicName As String) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Integer
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface StoretResultServiceChannel
        Inherits ResultServiceReference.StoretResultService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class StoretResultServiceClient
        Inherits System.ServiceModel.ClientBase(Of ResultServiceReference.StoretResultService)
        Implements ResultServiceReference.StoretResultService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function getResults(ByVal OrganizationId As String, ByVal MonitoringLocationId As String, ByVal MonitoringLocationType As String, ByVal MinimumActivityStartDate As String, ByVal MaximumActivityStartDate As String, ByVal MinimumLatitude As String, ByVal MaximumLatitude As String, ByVal MinimumLongitude As String, ByVal MaximumLongitude As String, ByVal CharacteristicType As String, ByVal CharacteristicName As String, ByVal ResultType As String) As String Implements ResultServiceReference.StoretResultService.getResults
            Return MyBase.Channel.getResults(OrganizationId, MonitoringLocationId, MonitoringLocationType, MinimumActivityStartDate, MaximumActivityStartDate, MinimumLatitude, MaximumLatitude, MinimumLongitude, MaximumLongitude, CharacteristicType, CharacteristicName, ResultType)
        End Function
        
        Public Function getResultCount(ByVal OrganizationId As String, ByVal MonitoringLocationId As String, ByVal MonitoringLocationType As String, ByVal MinimumActivityStartDate As String, ByVal MaximumActivityStartDate As String, ByVal MinimumLatitude As String, ByVal MaximumLatitude As String, ByVal MinimumLongitude As String, ByVal MaximumLongitude As String, ByVal CharacteristicType As String, ByVal CharacteristicName As String, ByVal ResultType As String) As Integer Implements ResultServiceReference.StoretResultService.getResultCount
            Return MyBase.Channel.getResultCount(OrganizationId, MonitoringLocationId, MonitoringLocationType, MinimumActivityStartDate, MaximumActivityStartDate, MinimumLatitude, MaximumLatitude, MinimumLongitude, MaximumLongitude, CharacteristicType, CharacteristicName, ResultType)
        End Function
        
        Public Function getActivityCount(ByVal OrganizationId As String, ByVal ActivityId As String, ByVal ActivityType As String, ByVal MonitoringLocationId As String, ByVal MonitoringLocationType As String, ByVal ProjectId As String, ByVal MinimumActivityStartDate As String, ByVal MaximumActivityStartDate As String, ByVal CharacteristicType As String, ByVal CharacteristicName As String) As Integer Implements ResultServiceReference.StoretResultService.getActivityCount
            Return MyBase.Channel.getActivityCount(OrganizationId, ActivityId, ActivityType, MonitoringLocationId, MonitoringLocationType, ProjectId, MinimumActivityStartDate, MaximumActivityStartDate, CharacteristicType, CharacteristicName)
        End Function
    End Class
End Namespace
